server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ckb_db
    username: ales
    password: ubuntu2023
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification_group