server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ckb_db
    username: postgres
    password: gattoVele
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
