githubDownloader:
  baseURL: http://api.github.com
  PersonalAccessToken: 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

sonarQube:
  accessToken: squ_eea4183c5d8215f5ecb3800076ff4fcf42e9d476

server:
  port: 8089

datasource:
  url: jdbc:postgresql://localhost:5432/ckb_db
  username: postgres
  password: Dolphin!
  driver-class-name: org.postgresql.Driver