githubDownloader:
    baseURL: http://api.github.com
    PersonalAccessToken: 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

server:
    port: 8090

datasource:
    url: jdbc:postgresql://localhost:5432/ckb_db
    username: postgres
    password: Dolphin!
    driver-class-name: org.postgresql.Driver