githubDownloader:
    baseURL: http://api.github.com
    PersonalAccessToken: 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

server:
    port: 8090

datasource:
    url: jdbc:postgresql://localhost:5432/ckb_db
    username: postgres
    password: Dolphin!
    driver-class-name: org.postgresql.Driver