server:
  port: 8083
  address: 0.0.0.0
  max-http-header-size: 10000000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ckb_db
    username: postgres
    password: gattoVele
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
#logging:
 # level:
  #  org.springframework: DEBUG
   # org.apache.coyote.http11: DEBUG

