server:
  port: 8083
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ckb_db
    username: ales
    password: ubuntu2023
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

